// <auto-generated />
using System;
using Kedu.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kedu.Infra.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126162034_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kedu.Domain.Entities.CentroDeCusto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome", "Tipo")
                        .IsUnique()
                        .HasDatabaseName("IX_CentrosDeCusto_Nome_Tipo");

                    b.ToTable("CentrosDeCusto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Matrícula",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Mensalidade",
                            Tipo = 2
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Material Escolar",
                            Tipo = 3
                        });
                });

            modelBuilder.Entity("Kedu.Domain.Entities.Cobranca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPagamento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MetodoPagamento")
                        .HasColumnType("integer");

                    b.Property<int>("PlanoDePagamentoId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPagamento")
                        .IsUnique()
                        .HasDatabaseName("IX_Cobrancas_CodigoPagamento");

                    b.HasIndex("DataVencimento")
                        .HasDatabaseName("IX_Cobrancas_DataVencimento");

                    b.HasIndex("PlanoDePagamentoId")
                        .HasDatabaseName("IX_Cobrancas_PlanoDePagamentoId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Cobrancas_Status");

                    b.ToTable("Cobrancas", (string)null);
                });

            modelBuilder.Entity("Kedu.Domain.Entities.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CobrancaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataPagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CobrancaId")
                        .HasDatabaseName("IX_Pagamentos_CobrancaId");

                    b.ToTable("Pagamentos", (string)null);
                });

            modelBuilder.Entity("Kedu.Domain.Entities.PlanoDePagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CentroDeCustoId")
                        .HasColumnType("integer");

                    b.Property<int>("ResponsavelFinanceiroId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CentroDeCustoId")
                        .HasDatabaseName("IX_PlanosDePagamento_CentroDeCustoId");

                    b.HasIndex("ResponsavelFinanceiroId")
                        .HasDatabaseName("IX_PlanosDePagamento_ResponsavelFinanceiroId");

                    b.ToTable("PlanosDePagamento", (string)null);
                });

            modelBuilder.Entity("Kedu.Domain.Entities.ResponsavelFinanceiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ResponsaveisFinanceiros", (string)null);
                });

            modelBuilder.Entity("Kedu.Domain.Entities.Cobranca", b =>
                {
                    b.HasOne("Kedu.Domain.Entities.PlanoDePagamento", "PlanoDePagamento")
                        .WithMany("Cobrancas")
                        .HasForeignKey("PlanoDePagamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoDePagamento");
                });

            modelBuilder.Entity("Kedu.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("Kedu.Domain.Entities.Cobranca", "Cobranca")
                        .WithMany("Pagamentos")
                        .HasForeignKey("CobrancaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cobranca");
                });

            modelBuilder.Entity("Kedu.Domain.Entities.PlanoDePagamento", b =>
                {
                    b.HasOne("Kedu.Domain.Entities.CentroDeCusto", "CentroDeCusto")
                        .WithMany("PlanosDePagamento")
                        .HasForeignKey("CentroDeCustoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Kedu.Domain.Entities.ResponsavelFinanceiro", "ResponsavelFinanceiro")
                        .WithMany("PlanosDePagamento")
                        .HasForeignKey("ResponsavelFinanceiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CentroDeCusto");

                    b.Navigation("ResponsavelFinanceiro");
                });

            modelBuilder.Entity("Kedu.Domain.Entities.CentroDeCusto", b =>
                {
                    b.Navigation("PlanosDePagamento");
                });

            modelBuilder.Entity("Kedu.Domain.Entities.Cobranca", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("Kedu.Domain.Entities.PlanoDePagamento", b =>
                {
                    b.Navigation("Cobrancas");
                });

            modelBuilder.Entity("Kedu.Domain.Entities.ResponsavelFinanceiro", b =>
                {
                    b.Navigation("PlanosDePagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
